name: Bug Report
description: Report a bug to help us improve
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you using?
      placeholder: e.g. 1.2.3
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste MelonLoader/latest.log here
      render: shell
    validations:
      required: false
